/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#424c3c",
        "surface-container-low": "#1a1c1a",
        "secondary-fixed-dim": "#bfcab5",
        "secondary-fixed": "#dbe6d0",
        "on-tertiary-container": "#758978",
        "surface": "#121412",
        "on-tertiary-fixed": "#0e1f13",
        "secondary": "#bfcab5",
        "outline-variant": "#454843",
        "on-background": "#e2e3df",
        "tertiary-fixed": "#d3e8d5",
        "surface-variant": "#333533",
        "inverse-primary": "#775a19",
        "outline": "#8f918c",
        "surface-tint": "#e9c176",
        "on-error-container": "#ffdad6",
        "background": "#121412",
        "surface-container": "#1e201e",
        "primary": "#e9c176",
        "tertiary-fixed-dim": "#b7ccb9",
        "surface-dim": "#121412",
        "on-tertiary": "#233427",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#394b3d",
        "surface-container-high": "#292a28",
        "on-primary": "#412d00",
        "surface-bright": "#383a37",
        "on-primary-fixed": "#261900",
        "surface-container-highest": "#333533",
        "on-surface-variant": "#c5c7c1",
        "on-secondary-container": "#b1bca7",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#5d4201",
        "primary-container": "#261900",
        "primary-fixed": "#ffdea5",
        "on-surface": "#e2e3df",
        "on-error": "#690005",
        "surface-container-lowest": "#0d0f0d",
        "on-secondary": "#293324",
        "inverse-surface": "#e2e3df",
        "tertiary": "#b7ccb9",
        "on-secondary-fixed-variant": "#404a3a",
        "on-secondary-fixed": "#151e11",
        "tertiary-container": "#0e1f13",
        "on-primary-container": "#a07f3b",
        "primary-fixed-dim": "#e9c176",
        "inverse-on-surface": "#2f312e"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
